# -*- coding: utf-8 -*-
import glob
import os
from os import path as osp
import inspect

import random
import jams
import numpy as np
import pandas as pd
import soundfile as sf
import scaper
from scaper import generate_from_jams

from .utils import add_event, choose_cooccurence_class, create_folder, get_labels_from_jams, _post_process_labels_file, choose_file
from .Logger import create_logger


def modify_bg_snr(new_snr, jam_file):
    """ Modify the background SNR of a JAMS generated by scaper
    Args:
        new_snr: float, Sound to noise ratio (SNR) of the background from the reference
        jam_file: str, the name of the JAMS file to change the background SNR

    Returns:
        jams object that has been modified
    """
    jam_obj = jams.load(jam_file)
    data = jam_obj["annotations"][0].data
    for cnt, obs in enumerate(data):
        if obs.value["role"] == "background":
            # Changing manually the jams to have the snr desired
            jam_obj["annotations"][0].data[cnt].value["snr"] = new_snr

    return jam_obj


def generate_new_bg_snr_files(new_snr, in_dir, out_dir, **kwargs):
    """ Generate the new JAMS and audio files with a different background SNR
    Args:
        new_snr: float, Sound to noise ratio (SNR) of the background from the reference
        in_dir: str, folder containing JAMS file with background SNR to be changed
        out_dir: str, folder where to save the new audio and JAMS
        kwargs: dict, scaper.generate_from_jams params

    Returns:

    """
    logger = create_logger(__name__ + "/" + inspect.currentframe().f_code.co_name)
    create_folder(out_dir)
    for jam_file in sorted(glob.glob(os.path.join(in_dir, "*.jams"))):
        jams_obj = modify_bg_snr(new_snr, jam_file)
        out_jams = osp.join(out_dir, os.path.basename(jam_file))
        jams_obj.save(out_jams)

        audiofile = os.path.join(out_dir, osp.splitext(osp.basename(jam_file))[0] + ".wav")
        logger.debug(audiofile)
        scaper.generate_from_jams(out_jams, audiofile, **kwargs)


def modify_fg_onset(added_value, jam_file):
    """ Add a value foreground onset of a JAMS generated by scaper (containing a single event)
    Args:
        added_value: float, value in seconds, value to be added to previous onset
        jam_file: str, the name of the JAMS file to change the background SNR

    Returns:
        jams object that has been modified
    """
    jam_obj = jams.load(jam_file)
    data = jam_obj["annotations"][0].data
    for cnt, obs in enumerate(data):
        if obs.value["role"] == "foreground":
            onset = obs.value["event_time"]
            # Change source time by adding the added value specified
            jam_obj["annotations"][0].data[cnt].value["event_time"] = onset + added_value
            # Todo, this is tricky, because it is an object, find a better way to do that with Scaper
            new_obs = jam_obj["annotations"][0].data[cnt]._replace(time=onset + added_value)
            del jam_obj["annotations"][0].data[cnt]
            jam_obj["annotations"][0].data.add(new_obs)

    return jam_obj


def generate_new_fg_onset_files(added_value, in_dir, out_dir, **kwargs):
    """ Generate the new JAMS and audio files adding a value to forground onsets
    Args:
        added_value: float, value in seconds, value to be added to previous onset
        in_dir: str, folder containing JAMS file with background SNR to be changed
        out_dir: str, folder where to save the new audio and JAMS
        kwargs: dict, scaper.generate_from_jams params
    Returns:

    """
    logger = create_logger(__name__ + "/" + inspect.currentframe().f_code.co_name)
    create_folder(out_dir)
    for jam_file in sorted(glob.glob(os.path.join(in_dir, "*.jams"))):
        jams_obj = modify_fg_onset(added_value, jam_file)
        out_jams = osp.join(out_dir, os.path.basename(jam_file))
        jams_obj.save(out_jams)

        audiofile = os.path.join(out_dir, osp.splitext(osp.basename(jam_file))[0] + ".wav")
        logger.debug(audiofile)
        scaper.generate_from_jams(out_jams, audiofile, **kwargs)


def initialize_scaper(duration, fg_folder, bg_folder, ref_db=None):
    """ Initialize scaper object with a reference dB.
    Args:
        duration: float, in seconds, the duration of the generated audio clip.
        fg_folder: str, path of foreground files (be careful, need subfolders, one per class or group)
        bg_folder: str, path of background files (be careful, need subfolders, one per group)
        ref_db: float, the reference dB of the clip.

    Returns:
        scaper.Scaper object

    """
    sc = scaper.Scaper(duration, fg_folder, bg_folder)
    sc.protected_labels = []
    if ref_db is not None:
        sc.ref_db = ref_db

    return sc


def add_random_background(scaper_obj):
    """ Add random background to a scaper object
    Args:
        scaper_obj: scaper.Scaper, the scaper object in which to add the background.

    Returns:
        scaper.Scaper object with background added.
    """
    chosen_file = choose_file(osp.join(scaper_obj.bg_path, "*"))
    file_duration = sf.info(chosen_file).duration
    starting_source = min(random.random() * file_duration, max(file_duration - scaper_obj.duration, 0))
    scaper_obj.add_background(label=('const', chosen_file.split("/")[-2]),
                              source_file=('const', chosen_file),
                              source_time=('const', starting_source))
    return scaper_obj


def generate_single_file(class_params, class_lbl, duration, fg_folder, bg_folder, outfolder, filename, ref_db=None,
                         min_events=0, reverb=0.1, **kwargs):
    """ Generate a single file, using the information of onset or offset present
    (see DESED dataset and folders in soundbank foreground)
    Args:
        class_params: dict, dict containing information about how to mix classes, and the probability of each class.
        class_lbl: str, the main foreground label of the generated file.
        duration: float, in seconds, the duration of the generated audio clip.
        fg_folder: str, path of foreground files (be careful, need subfolders, one per class or group)
        bg_folder: str, path of background files (be careful, need subfolders, one per group)
        outfolder: str, path to extract generate file
        filename: str, name of the generated file, without extension (.wav, .jams and .txt will be created)
        ref_db: float, the reference dB of the clip.
        min_events: int, the minimum number of events to add (on top of the main event), maximum is in class_params.
        reverb: float, the reverb to be applied to the foreground events
        kwargs: arguments accepted by Scaper.generate
    Returns:
        None
    """
    # create a scaper
    sc = initialize_scaper(duration, fg_folder, bg_folder, ref_db=ref_db)
    sc = add_random_background(sc)

    # add main event
    sc = add_event(sc, class_lbl)

    # add random number of foreground events
    n_events = np.random.randint(min_events, class_params['event_max'])
    for _ in range(n_events):
        chosen_class = choose_cooccurence_class(class_params)
        sc = add_event(sc, chosen_class)

    # generate
    audiofile = osp.join(outfolder, f"{filename}.wav")
    jamsfile = osp.join(outfolder, f"{filename}.jams")
    txtfile = osp.join(outfolder, f"{filename}.txt")

    sc.generate(audiofile, jamsfile,
                reverb=reverb,
                txt_path=txtfile,
                **kwargs)


def generate_files_from_jams(list_jams, outfolder, overwrite_jams=False, save_isolated_events=False,
                             isolated_events_path=None,  **kwargs):
    """ Generate audio files from jams files generated by Scaper

    Args:
        list_jams: list, list of jams filepath generated by Scaper.
        outfolder: str, output path to save audio files.
        overwrite_jams: bool, overwrite the input JAMS with generated ones (update fg and bg path for example)
        save_isolated_events: bool, whether or not to save isolated events in a separate folder
        isolated_events_path: str, only useful when save_isolated_events=True. Give the path to the events folders.
            If None, a folder is created next to the audio files.
        kwargs: dict, scaper.generate_from_jams params
    Returns: None

    """
    logger = create_logger(__name__ + "/" + inspect.currentframe().f_code.co_name)
    logger.info(f"generating audio files to {outfolder}")
    create_folder(outfolder)
    for n, jam_file in enumerate(list_jams):
        logger.debug(jam_file)
        audiofile = osp.join(outfolder, f"{osp.splitext(osp.basename(jam_file))[0]}.wav")
        if overwrite_jams:
            jams_outfile = jam_file
        else:
            jams_outfile = None
        generate_from_jams(jam_file, audiofile, jams_outfile=jams_outfile,
                           save_isolated_events=save_isolated_events,
                           isolated_events_path=isolated_events_path,
                           **kwargs)

        if n % 200 == 0:
            logger.info(f"generating {n} / {len(list_jams)} files (updated every 200)")
    logger.info("Done")


def generate_multi_common(number, duration, fg_folder, bg_folder, outfolder, min_events, max_events, ref_db=None,
                          labels=('choose', []), source_files=('choose', []), sources_time=('const', 0),
                          events_start=('truncnorm', 5.0, 2.0, 0.0, 10.0), events_duration=('uniform', 0.25, 10.0),
                          snrs=('const', 30), pitch_shifts=('uniform', -3.0, 3.0), time_stretches=('uniform', 1, 1),
                          txt_file=True, **kwargs):
    """ Generate

    Args:
        number: int, number of audio clips to create.
        duration: float, in seconds, the duration of the clip
        fg_folder: str, path of foreground files (be careful, need subfolders, one per class or group)
        bg_folder: str, path of background files (be careful, need subfolders, one per group)
        outfolder: str, path to extract generate file
        min_events: int, the minimum number of foreground events to add (pick at random uniformly).
        max_events: int, the maximum number of foreground events to add (pick at random uniformly).
        ref_db: float, the dB reference of the clip
        labels: tuple or list, strategy to choose foreground events (see Scaper) or list of events.
        source_files: tuple or list, strategy to choose source files (see Scaper) or list of source files.
        sources_time: tuple or list, strategy to choose source start time (see Scaper) or list of sources start time.
        events_start: tuple or list, strategy to choose events start time (see Scaper) or list of events start time.
        events_duration: tuple or list, strategy to choose events duation (see Scaper) or list of events duration.
        snrs: tuple or list, strategy to choose foreground to background SNRs (see Scaper) or list of SNRs.
        pitch_shifts: tuple or list, strategy to choose pitch shift (see Scaper) or list of pitch shifts.
        time_stretches: tuple or list, strategy to choose time stretches (see Scaper) or list of time stretches.
        txt_file: bool, whether or not to save the .txt file.
        kwargs: arguments accepted by Scaper.generate

    Returns:
        None
    """
    logger = create_logger(__name__ + "/" + inspect.currentframe().f_code.co_name)
    params = {
        'labels': labels,
        'source_files': source_files,
        'sources_time': sources_time,
        'events_start': events_start,
        'events_duration': events_duration,
        'snrs': snrs,
        'pitch_shifts': pitch_shifts,
        'time_stretches': time_stretches
    }

    for n in range(number):
        logger.debug('Generating soundscape: {:d}/{:d}'.format(n + 1, number))
        # create a scaper
        n_events = np.random.randint(min_events, max_events + 1)
        generate_one_bg_multi_fg(duration=duration,
                                 fg_folder=fg_folder,
                                 bg_folder=bg_folder,
                                 out_folder=outfolder,
                                 filename=n,
                                 n_fg_events=n_events,
                                 ref_db=ref_db,
                                 **params,
                                 txt_file=txt_file,
                                 **kwargs)


def generate_tsv_from_jams(list_jams, tsv_out, post_process=True, background_label=False):
    """ In scaper.generate they create a txt file for each audio file.
    Using the same idea, we create a single tsv file with all the audio files and their labels.
    Args:
        list_jams: list, list of paths of JAMS files. Assume WAV files have the same name as JAMS files.
        tsv_out: str, path of the tsv to be saved
        post_process: bool, post_process removes small blanks, clean the overlapping same events in the labels and
        make the smallest event 250ms long.
        background_label: bool, include the background label in the annotations.
        # source_sep_path: str, the path to save the csv of separated source files. Assume

    Returns:
        None
    """
    create_folder(osp.dirname(tsv_out))
    final_df = pd.DataFrame()
    for jam_file in list_jams:
        print(jam_file)
        fbase = osp.basename(jam_file)
        df, length = get_labels_from_jams(jam_file, background_label=background_label, return_length=True)

        if post_process:
            df, _ = _post_process_labels_file(df, length)

        df["filename"] = f"{osp.splitext(fbase)[0]}.wav"
        final_df = final_df.append(df[['filename', 'onset', 'offset', 'event_label']], ignore_index=True)

    final_df = final_df.sort_values(by=["filename", "onset"])
    final_df.to_csv(tsv_out, sep="\t", index=False, float_format="%.3f")


def generate_one_bg_multi_fg(duration, fg_folder, bg_folder, out_folder, filename, n_fg_events, ref_db=None,
                             labels=('choose', []), source_files=('choose', []), sources_time=('const', 0),
                             events_start=('truncnorm', 5.0, 2.0, 0.0, 10.0), events_duration=("uniform", 0.25, 10.0),
                             snrs=("const", 30), pitch_shifts=('uniform', -3.0, 3.0),
                             time_stretches=('uniform', 1, 1), reverb=0.1, txt_file=True,
                             save_isolated_events=False, isolated_events_path=None,
                             **kwargs):
    """ Generate a clip with a background file and multiple foreground files
    Args:
        duration: float, in seconds, the duration of the clip
        fg_folder: str, path of foreground files (be careful, need subfolders, one per class or group)
        bg_folder: str, path of background files (be careful, need subfolders, one per group)
        out_folder: str, path to extract generate file
        filename: str, name of the generated file, without extension (.wav, .jams and .txt will be created)
        n_fg_events: int, the number of foreground events to add
        ref_db: float, the dB reference of the clip
        labels: tuple or list, strategy to choose foreground events (see Scaper) or list of events.
        source_files: tuple or list, strategy to choose source files (see Scaper) or list of source files.
        sources_time: tuple or list, strategy to choose source start time (see Scaper) or list of sources start time.
        events_start: tuple or list, strategy to choose events start time (see Scaper) or list of events start time.
        events_duration: tuple or list, strategy to choose events duation (see Scaper) or list of events duration.
        snrs: tuple or list, strategy to choose foreground to background SNRs (see Scaper) or list of SNRs.
        pitch_shifts: tuple or list, strategy to choose pitch shift (see Scaper) or list of pitch shifts.
        time_stretches: tuple or list, strategy to choose time stretches (see Scaper) or list of time stretches.
        reverb: float, the reverb to be applied to the foreground events
        txt_file: bool, whether or not to save the .txt file.
        save_isolated_events: bool, whether or not to save isolated events in a separate folder
        isolated_events_path: str, only useful when save_isolated_events=True. Give the path to the events folders.
            If None, a folder is created next to the audio files.
        kwargs: arguments accepted by Scaper.generate
    Returns:
        None
    """
    sc = initialize_scaper(duration, fg_folder, bg_folder, ref_db=ref_db)
    sc = add_random_background(sc)

    params = {"label": labels, "source_file": source_files, "source_time": sources_time, "event_time": events_start,
              "event_duration": events_duration, "snr": snrs, "pitch_shift": pitch_shifts,
              "time_stretch": time_stretches}
    for i in range(n_fg_events):
        event_params = {}
        for key in params:
            if type(params[key]) is tuple:
                param = params[key]
            elif type(params[key]) is list:
                assert len(params[key]) == n_fg_events
                param = params[key][i]
            else:
                raise NotImplementedError("Params of events is tuple(same for all) or list (different for each event)")
            event_params[key] = param

        sc.add_event(**event_params)

    # generate
    audiofile = osp.join(out_folder, f"{filename}.wav")
    jamsfile = osp.join(out_folder, f"{filename}.jams")
    if txt_file:
        # Can be useless if you want background annotation as well, see post_processing_annotations.
        txtfile = osp.join(out_folder, f"{filename}.txt")
    else:
        txtfile = None
    sc.generate(audio_path=audiofile, jams_path=jamsfile,
                reverb=reverb,
                txt_path=txtfile,
                save_isolated_events=save_isolated_events,
                isolated_events_path=isolated_events_path,
                **kwargs)
